aeecleclair/Hyperion

Dockerfile
Add a production dockerfile in order to create the docker image
=> [docker] Dockerfile

.github/workflows/lintandformat.yml, .github/workflows/test.yml
=> Use two distinct GitHub workflows

app/cruds/cruds_users.py, app/endpoints/users.py, app/schemas/schemas_core.py, app/utils/examples/examples_core.py
(TODO: fix a problem of circular import with schemas_core in cruds_user)
Add Patch Users
=> Add Patch Users

README.md
=> Add a description for Hyperion

app/cruds/cruds_groups.py, app/endpoints/groups.py, app/endpoints/users.py, app/models/models_core.py, app/schemas/schemas_core.py, app/utils/types/groups_type.py, tests/commons.py, tests/test_groups.py, tests/test_users.py
- Improve groups endpoints permissions and data validation
- Add a description field to membership
- Document code
- Add basic tests for groups endpoints
=> Groups improvements

app/cruds/cruds_users.py, app/endpoints/auth.py, app/endpoints/users.py, app/schemas/schemas_core.py, app/utils/examples/examples_core.py, app/utils/types/standard_responses.py, templates/activation.html, templates/error.html, tests/test_auth.py, tests/test_users.py
- fix(auth) PKCE code verifier verification
- feat(user) include and excludes filter in the search endpoint
- feat(user) batch account creation endpoint
- feat(user) improve account creation and activation process (email regex...)
- feat(user) endpoint to make the first user admin
- feat(html) account activation page
=> Users management

app/utils/auth/providers.py
=> Add HedgeDoc Client

app/cruds/cruds_amap.py, app/endpoints/amap.py, app/models/models_amap.py, app/schemas/schemas_amap.py
AMAP: Add an `order` relationship to deliveries to fix get order from delivery
=> AMAP: Add an `order` relationship to deliveries

app/endpoints/auth.py, app/endpoints/users.py, app/models/models_core.py, app/schemas/schemas_auth.py, app/schemas/schemas_core.py, app/utils/validators.py
=> fix(users): force the user to provide a password during activation

app/dependencies.py, app/endpoints/auth.py, app/utils/auth/providers.py, app/utils/types/scopes_type.py
=> Add scope "profile" to access user info endpoint without openid

app/endpoints/users.py, app/models/models_core.py, app/schemas/schemas_core.py, app/utils/examples/examples_core.py, app/utils/types/floors_type.py, app/utils/validators.py, tests/commons.py, tests/test_auth.py, tests/test_users.py
- Add a floor enumeration
- Support new email address
- Prevent users from changing their name and firstname
- Return phone numbers
A database migration may be required
=> Core User creation promo and floor

app/core/config.py, app/core/security.py, app/dependencies.py, app/main.py, app/models/models_core.py
Add logging in dependencies and security functions
Add a dummy hash verification to prevent timing attacks
Log 422 validation errors on debug level
=> Security improvements

app/core/log.py, app/endpoints/auth.py, app/endpoints/groups.py, app/main.py, app/utils/loggers_tools/matrix_handler.py
=> Improve logging

app/cruds/cruds_calendar.py, app/endpoints/calendar.py, app/models/models_calendar.py, app/schemas/schemas_calendar.py, app/utils/types/calendar_types.py, tests/test_calendar.py
=> Calendar improvement

app/cruds/cruds_bdebooking.py, app/endpoints/bdebooking.py, app/models/models_bdebooking.py, app/schemas/schemas_bdebooking.py, tests/test_bdebooking.py
Return applicant's information with booking and add booking entity
=> Booking improvement

app/cruds/cruds_amap.py, app/endpoints/amap.py, tests/test_amap.py
Fix some concurrents commit in db
Fix uses of some undefined variable
=> fix create_delivery

app/utils/auth/providers.py
Added an auth provider for the minecraft server
=> Add Minecraft auth provider

app/cruds/cruds_amap.py, app/cruds/cruds_groups.py, app/cruds/cruds_users.py, app/dependencies.py, app/endpoints/admin.py, app/endpoints/amap.py, app/endpoints/bdebooking.py, app/endpoints/calendar.py, app/endpoints/campaign.py, app/endpoints/users.py, app/models/models_amap.py, app/schemas/schemas_calendar.py, app/utils/redis.py, tests/commons.py, tests/test_amap.py, tests/test_bdebooking.py, tests/test_calendar.py, tests/test_users.py
Fix several issues before publishing MyECL v0.5
=> Fixes for MyECL v0.5

app/utils/auth/providers.py
=> add challenger auth provider

app/cruds/cruds_amap.py, tests/test_bdebooking.py
Fix issues related to foreign keys when removing specific rows in AMAP
Fix booking's tests when deleting a room linked to existing bookings (error is the normal behavior)
=> Fix delete when foreign keys

.env, app/core/config.py, app/core/log.py, app/endpoints/amap.py
Add a logger specific to Amap that log in a file and in a dedicated matrix room
=> Add amap logger and handler

.github/workflows/publish.yml
Add workflow to build and push a docker image of Hyperion for each pull request and new release.
=> add docker workflow

app/endpoints/users.py, tests/test_users.py
Add an endpoint to get one's own profile picture and require an authenticated user to get a profile picture
=> Profile picture

app/endpoints/amap.py
Enable users to order without enough money
=> AMAP features

app/endpoints/amap.py, tests/test_amap.py
- Allow amap admin to remove orders from a locked delivery.
=> allow amap admin to remove orders when delivery is locked

app/endpoints/amap.py
=> add log when changing cash

app/utils/auth/providers.py
Fix parenthesis issue in display name
=> Fix Nextcloud auth provider

app/endpoints/users.py
=> Allow download profile-picture without beeing a member

app/cruds/cruds_calendar.py, app/endpoints/calendar.py
=> update ical on approve

app/endpoints/users.py, app/schemas/schemas_core.py
=> Allows admin to change an user name, firsname and promo

docker-compose-dev.yaml
=> Hyperion: fix missing volume declaration

app/utils/auth/providers.py
add openproject userinfo provider
=> Openproject userinfo provider

app/endpoints/campaign.py
=> Fix delete all lists in campaign module

app/utils/types/calendar_types.py
=> Add "independent association" CalendarEventType

app/cruds/cruds_calendar.py, app/endpoints/calendar.py
- fix RRULE when creating iCal file
- add an endpoint to allow global admin to manually create iCal file
Refs for RRULE fix : 
https://stackoverflow.com/questions/20143590/how-to-add-rrule-to-icalendar-event-in-python
https://icalendar.readthedocs.io/en/latest/_modules/icalendar/prop.html#vRecur
=> Fix ical rrule

.vscode/settings.json
=> Fix settings.json because for VSCode's extension

.vscode/settings.json
Allows to run tests from VS Code while adding breakpoints and having access to all logs
=> VS Code configuration for Pytest

app/app.py, app/cruds/cruds_users.py, app/endpoints/users.py, app/models/models_core.py, app/schemas/schemas_core.py, app/utils/tools.py, requirements-dev.txt, tests/commons.py, tests/test_users.py
=> Add email migration endpoints

app/endpoints/users.py, app/utils/types/groups_type.py
- fix regex dots which were not escaped
- allow centraliens-lyon.net to sign up
=> Fix email regex

.env, .env.test, .gitignore, README.md, app/api.py, app/core/config.py, app/cruds/cruds_cinema.py, app/cruds/cruds_notification.py, app/dependencies.py, app/endpoints/cinema.py, app/endpoints/notification.py, app/models/models_notification.py, app/schemas/schemas_notification.py, app/utils/communication/notifications.py, app/utils/types/notification_types.py, app/utils/types/tags.py, docker-compose.yaml, requirements.txt
=> Notification

.vscode/extensions.json, .vscode/settings.json
Ref: https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions
=> Add recommended extensions

app/endpoints/core.py, assets/robots.txt
Add robots.txt file
Disallow search engines to index Hyperion's webpages
Solve #237
=> Add robots.txt

app/endpoints/auth.py
=> Clean #242

app/endpoints/advert.py, app/endpoints/amap.py, app/endpoints/bdebooking.py, app/models/models_notification.py, app/utils/types/notification_types.py
Add notifications on other modules
=> Notifications adding modules

app/endpoints/users.py
Fixed typo in email migration email's subject.
=> typo in email migration email subject

app/utils/communication/notifications.py
Add android config and apnsconfig
Fix priority on android
Set background notification on ios
=> Add androidconfig and apnsconfig

app/cruds/cruds_campaign.py, app/endpoints/campaign.py, app/models/models_campaign.py, app/schemas/schemas_campaign.py, app/utils/types/groups_type.py, tests/test_campaign.py
=> Campaign-authorization

.github/workflows/test.yml
Run the test workflow on main so that the coverage from pull request can be compared to main
=> run test on push on main

.github/codecov.yml, README.md
to allow coverage to be reduced by a few percent
=> Add Codecov.yml config file

app/endpoints/groups.py
to allow users to use the Campaign module
=> Allow all users to get groups

app/endpoints/booking.py
which raised `send_notification_to_topic() got an unexpected keyword argument 'topic'`
fix: #306
=> Fix cinema notification

.github/workflows/publish.yml, Dockerfile
=> Change Dockerfile order to improve performances

app/modules/calendar/types_calendar.py
=> Fix: Changes CalendarEventType enum to match Titan 

app/modules/booking/endpoints_booking.py, migrations/versions/4-fix_datetime.py
Migration file of the PR #360 is incomplete. The goal of this PR is to add the forgotten columns.
=> DateTime migration file

app/utils/tools.py, pyproject.toml, tests/test_utils.py
=> Only allow to use a uuid to get_file_from_data

app/core/users/endpoints_users.py, tests/test_users.py
=> Add tests for user endpoints

migrations/versions/3-fix_datetime.py
A migration file that should fix the wrong timestamp with timezone currently stored in our PostgreSQL database and that should converts the timestamp with timezone to timestamp without timezone.
=> Fix datetime migration

migrations/versions/7-notifications_create_on.py
=> Add migration for notifications create_on row

app/app.py, migrations/env.py
- support `AsyncConnection` in addition to `Connection`
- improve documentation about connections and connectable
- improve documentation about migrations internal logic
- clean and improve migration internal logic
=> Refactor Alembic migration internal logic

app/core/users/endpoints_users.py, app/modules/advert/endpoints_advert.py, app/modules/campaign/endpoints_campaign.py, app/modules/cinema/endpoints_cinema.py, app/modules/phonebook/endpoints_phonebook.py, app/modules/raffle/endpoints_raffle.py, app/modules/recommendation/endpoints_recommendation.py, app/types/content_type.py, app/utils/tools.py, tests/test_utils.py
=> Only allow content-type based on an enum for saving files

app/app.py
We should also rate limit unknown clients.
=> Rate limit unknown clients

.env.template, .env.test, README.md, app/core/config.py, app/modules/cinema/endpoints_cinema.py, app/modules/cinema/schemas_cinema.py, tests/test_cinema.py
Send request to the movie API from Hyperion.
=> Send movie db request through Hyperion

app/modules/cinema/endpoints_cinema.py, app/modules/loan/endpoints_loan.py, app/utils/communication/date_manager.py
=> Send cinema and loan notifications at the right delivery_datetime

.env.template, .env.test, app/core/config.py, app/modules/cinema/endpoints_cinema.py
IMDb > TMDb, unless it's related to pasting the IMDb link on the admin page
=> Replacing IMDb with TMDb

app/modules/cinema/endpoints_cinema.py
If we add a film this week the release date of the notification is last sunday so it triggers notification now. That is not what we want.
- [ x ] All tests passing
=> Cinema notif on current week film

app/app.py, app/core/log.py, app/utils/loggers_tools/matrix_handler.py
- remove log duplication
- enable logs from other libraries
- log if matrix handler is enabled or disabled after initialization of loggers
=> Fix bugs in log system

.vscode/launch.json, README.md
Fixed #462 issue by using FastAPI CLI for local setup
=> Use FastAPI CLI for local setup

.env.template, .env.test, app/core/auth/endpoints_auth.py, app/core/config.py, tests/test_auth.py
=> Support oauth-authorization-server wellknown discovery and simplify dotenv config

app/utils/tools.py
=> Fix user sorting

.env.template, README.md, app/core/config.py, app/core/endpoints_core.py, app/types/exceptions.py, app/utils/google_api/README.md, app/utils/google_api/coredata_google_api.py, app/utils/google_api/google_api.py, pyproject.toml, requirements-common.txt
=> Google API

app/modules/cdr/endpoints_cdr.py, tests/test_cdr.py
=> Endpoint permission and product variant deactivation

.env.template, requirements-common.txt
=> Bump calypsso to 1.1.2 and complete .env.template

app/modules/cdr/schemas_cdr.py, tests/test_cdr.py
=> CDR: Allow to update promo, birthday and phone

app/modules/cdr/endpoints_cdr.py, app/modules/cdr/schemas_cdr.py
=> Cdr migrate info

app/modules/cdr/endpoints_cdr.py, app/types/websocket.py
=> Remove ws connection after unsubscribe

app/core/config.py, app/core/users/cruds_users.py, app/core/users/endpoints_users.py, app/utils/mail/mailworker.py, tests/test_user_fusion.py
=> Feat: clean and bump version

app/app.py
=> Init Google API authentication when google is configured in dotenv

app/modules/cdr/utils_cdr.py
=> Fix Dataframe NaN removal

app/core/config.py
=> Bump version to 3.0.1 and Titan minimal version to 130

app/core/config.py, app/modules/cdr/cruds_cdr.py, app/modules/cdr/endpoints_cdr.py, app/modules/cdr/utils_cdr.py, tests/test_cdr.py
=> Fix cdr result

app/core/config.py, app/core/users/endpoints_users.py, tests/test_users.py
=> Fix email migration

app/modules/cinema/cruds_cinema.py
=> Fix : cine notif order

app/core/users/endpoints_users.py
=> User email migration and batch internal

app/core/users/endpoints_users.py
=> Fix batch internal users

app/core/models_core.py, app/core/users/endpoints_users.py, tests/test_users.py
=> Fix internal user

app/modules/flappybird/cruds_flappybird.py, app/modules/flappybird/endpoints_flappybird.py, tests/test_flappybird.py
Added crud, endpoint and test for deleting FlappyBirdBestScore
Need thorough reviewing (first PR)
=> [FlappyBird] Added delete best score functionnality

app/utils/communication/notifications.py
Logging a warning would allow finding in which situation we send a notification without having any tokens
=> Notification without token

app/utils/auth/auth_utils.py
=> Ignore "not enough segment" error with JWT

app/dependencies.py, app/modules/cdr/endpoints_cdr.py, app/types/websocket.py, tests/commons.py, tests/conftest.py
=> Close db in websocket

requirements-common.txt
=> Bump CalypSSO to 1.2.0

app/core/config.py
=> Feat: bump titan minimal

requirements-common.txt
=> Update fastapi requirement

app/modules/ph/endpoints_ph.py
This should resolve issue #635
=> Fixed: changed file format of a default cover from .jpg to .jpeg

app/core/config.py
=> Bump Titan minimal version

app/core/auth/endpoints_auth.py
=> Fix: temporary measure to accept PKCE with secret

app/modules/purchases/endpoints_purchases.py
=> Add purchases module declaration

app/core/config.py
* Enough changes worth a minor have occurred (regarding Schools, SQLite support, Planka and security issues due to Jinja)
* Doing this minor before more be merged
=> Bump version

app/utils/auth/providers.py
Add the auth provider for the new service Slash (URL shortener).
=> Add auth provider slash

app/core/utils/config.py
No breaking changes were brought in the seed library
=> Fix: decrease the minimal Titan version

app/core/memberships/endpoints_memberships.py, app/core/utils/config.py
=> Fix membership and bump version

app/core/myeclpay/cruds_myeclpay.py, app/core/myeclpay/endpoints_myeclpay.py
=> Myeclpay fix

app/core/payment/endpoints_payment.py, app/core/payment/payment_tool.py, app/core/payment/types_payment.py, app/types/exceptions.py, requirements-common.txt, requirements-dev.txt, tests/test_payment.py
Replace the previous handmade api wrapper by the new official sdk
=> Use new HelloAsso SDK

.env.template, app/core/myeclpay/cruds_myeclpay.py, app/core/myeclpay/endpoints_myeclpay.py, app/core/myeclpay/integrity_myeclpay.py, app/core/myeclpay/types_myeclpay.py, app/core/myeclpay/utils_myeclpay.py, app/core/utils/config.py, app/core/utils/log.py, app/dependencies.py, app/types/exceptions.py, app/types/s3_access.py, app/utils/loggers_tools/s3_handler.py, requirements-common.txt, requirements-dev.txt
=> Myeclpay logs

app/core/myeclpay/cruds_myeclpay.py, app/core/myeclpay/endpoints_myeclpay.py
- allow to unset a required membership when patching a structure
- return the membership relationship when creating the structure
=> Fix : add and edit structure

app/modules/flappybird/endpoints_flappybird.py
There is an unprotected endpoint that gives access to data from every user that played
=> Free access to flappy bird data

app/core/myeclpay/endpoints_myeclpay.py
Allow read (GET) to:
* wallet (especially to display the balance)
* the device information
=> Allow read access even when last ToS are refused

app/modules/raid/cruds_raid.py, app/modules/raid/endpoints_raid.py
Mandatory fixes before openning the registering for 2025 edition
=> feat(raid): delete invite and Google Drive PDF when deleting teams

pyproject.toml
=> Release 4.5.4

app/core/payment/payment_tool.py, app/core/utils/log.py
=> Don't log exception trace before retrying HA Payment

app/modules/raid/coredata_raid.py, app/modules/raid/endpoints_raid.py, app/modules/raid/models_raid.py, tests/commons.py, tests/test_raid.py
Goes hand to hand with : https://github.com/aeecleclair/raid-registering/pull/58
=> Feat  raid different prices

app/core/myeclpay/endpoints_myeclpay.py, requirements-common.txt
The link in the mail asserting you signed the ToS now brings to a less austere page.
=> MyECLPay: use new CalypSSO UI for text assets

.env.template.yaml, .env.test.yaml, app/core/utils/config.py, app/types/exceptions.py
instead of a list of list
This PR introduce a breaking change
Requires https://github.com/aeecleclair/Hyperion/pull/756
=> Allow to configure AuthClients using a dictionnary

Dockerfile
=> Removed old init.py

Dockerfile
=> Change Dockerfile entrypoint to adapt new env_file parameter

app/utils/initialization.py
=> Invert logic for unlock_key

app/modules/cdr/schemas_cdr.py
=> Remove useles attribute

app/module.py, app/modules/cdr/cruds_cdr.py, app/modules/cdr/endpoints_cdr.py, tests/test_cdr.py
=> Hotfix cdr

pyproject.toml
=> Bump version to 4.7.1

app/modules/cdr/endpoints_cdr.py
=> CDR : open result endpoint to sellers

app/modules/raid/cruds_raid.py, app/modules/raid/endpoints_raid.py
When deleting all teams, participants must be deleted as well
=> fix: deleting all participant along all teams

app/modules/raid/utils/utils_raid.py
=> Raid : handling both prices

app/modules/sport_competition/cruds_sport_competition.py, app/modules/sport_competition/endpoints_sport_competition.py, app/modules/sport_competition/schemas_sport_competition.py, pyproject.toml, tests/sport_competition/test_purchases.py, tests/sport_competition/test_sport_inscription.py
=> IC Challenger: school product's quota

pyproject.toml
=> Bump version to 4.9.2
