aeecleclair/Hyperion

- app/utils/auth/providers.py
To test endpoints requiring authentication using [Postman](https://www.postman.com/) we can use this `PostmanAuthClient`.
1. Register the client in Hyperion dotenv `.env`:
```python
AUTH_CLIENTS=[["Postman", "PostmanSecret", "PostmanAuthClient"]]
```
2. Configure Postman to use `OAuth 2.0` authorization:
> Grant Type: `Authorization code`
> [x] Authorize using browser
> Auth URL: http://127.0.0.1:8000/auth/authorize
> Access Token URL: http://127.0.0.1:8000/auth/token
> Client ID: `Postman`
> Client Secret: `PostmanSecret`
> Scope: `API`
> Postman auth client

- app/endpoints/bdebooking.py
- app/endpoints/users.py
- tests/test_bdebooking.py
- tests/test_users.py
Titan would support PATCH requests to return either 204 No Content or 200 with the modified object. 
Unless Titan specifically requires the modified to be returned, in an effort of uniformization, let Hyperion return 204.
> Return a 204 http code when succeeding a PATCH request

- app/utils/loggers_tools/matrix_handler.py
Even when disabled, the matrix handler tried to open a connection with Matrix website. This prevented Hyperion from starting when no internet access was available.
> Don't try to connect Matrix handler when disabled

- app/endpoints/amap.py
Cash should be created when ordering if it does not exist already. Allow users to order before the admin increased its balance
> Create cash if not exists when ordering

- app/utils/auth/providers.py
Fix `/users/{user.id}/profile-picture` in auth providers.
Trailing slash leaded to issues with some services which don't follow the redirection
> Fix profile picture trailing slash

- .env
- .env.test
- app/core/config.py
- app/main.py
- tests/test_core.py
- configure CORS middleware after startup to allow tests to use the mocked Config class
- add a test for CORS success and failure
- document allowed origins format
> Test CORS configuration

- .vscode/settings.json
Disable .env handling by VSCode, which leads to issues when debugging
> Fix .env for debugging

- app/endpoints/users.py
> Remove additional "/" in email migration

- app/endpoints/campaign.py
- app/endpoints/cinema.py
- app/endpoints/core.py
- app/endpoints/raffle.py
- app/endpoints/users.py
- app/utils/tools.py
Mitigate few security issues related to `get_file_from_data`:
- on some modules, endpoints are accessible for unauthenticated users
- wildcards interpreted by glob.glob() can be exploited to enumerate user ids and profile pictures without being authenticated
> get_file_from_data mitigation

- app/cruds/cruds_notification.py
- app/endpoints/advert.py
- app/endpoints/amap.py
- app/endpoints/bdebooking.py
- app/endpoints/cinema.py
- app/endpoints/notification.py
- app/models/models_notification.py
- app/utils/communication/notifications.py
- app/utils/types/notification_types.py
- Various fix when calling send_notification_to_user
- Fix notifications title
- Fix CustomTopic to_str() which lead to send wrongly formatted topic names to Titan
- Add get_topit_identifier to get full topic name (with identifiers) the user is subscribed to for a given topic
-  Rename get_topic_membership_XX to plural & add get_topic_memberships_by_user_id_and_topic
> Fix notifications

- app/cruds/cruds_campaign.py
to not delete a list when Votes are still referring to it as a foreign key
This prevent a SQLAlchemy error
```
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) : update or delete on table "campaign_lists" violates foreign key constraint "campaign_votes_list_id_fkey" on table "campaign_votes" | DETAIL: Key (id)=(84073848-4167-42e4-91fb-b090aad3087d) is still referenced from table "campaign_votes". | [SQL: DELETE FROM campaign_lists WHERE campaign_lists.type = $1::VARCHAR] | [parameters: (,)] | (Background on this error at: https://sqlalche.me/e/20/gkpj)
```
> Delete Blank list after removing Votes

- app/core/security.py
- requirements.txt
Use the bcrypt library for password hashing instead of passlib that used a deprecated dependency (crypt).
> Use bcrypt instead of passlib

- tests/test_users.py
Fixed test_users::test_search_users.
When there were more than 10 users in the students group, it would fail because it would try to compare all of the users from the group to the users returned by an endpoint that is limited to return up to 10 users only.
I've modified the test so that instead of a strict equality, it is now an inequality, meaning that the students returned by /users/search must be present in the group, but we don't need all of them
> Fix test_search_users

- pyproject.toml
The coverage tool does not automatically mark as covered the functions that use greenlet, so all the functions that used sqlalchemy were incorrectly marked as not covered.
This PR adds the relevant option in pyproject.toml.
> Fix concurrency for coverage in pyproject.toml

- app/endpoints/calendar.py
- app/endpoints/raffle.py
- app/schemas/schemas_raffle.py
Fix some responses models in endpoints:
> Fix response model

- .vscode/settings.json
- app/core/config.py
Update VSCode workspace settings to fix black formatting issues.
VSCode "Black Formatter" extension ships with its own version of black. This PR enforces the use of the local install of black, which should match the `requirements-dev.txt`.
> Fix black formatting

- .github/workflows/lintandformat.yml
- .github/workflows/test.yml
- README.md
This PR edits the few places in the repo to use python 3.11 for unit tests and when creating a new virtual environment. 
Currently, everything is a bit mismatched, the production docker image is on 3.11 while the ci/cd runs on 3.10 and the readme tells to use 3.11 under macos but 3.10 under windows.
> Use python 3.11 in leftover parts

- app/core/notification/models_notification.py
- app/core/notification/schemas_notification.py
Use datetime for expire_on instead of date.
This PR fixes the error `Datetimes provided to dates should have zero time - e.g. be exact dates [type=date_from_datetime_inexact, input_value=datetime.datetime(2024, 3...Paris' CET+1:00:00 STD>), input_type=datetime]`
> Fix notifications create_on

- app/modules/advert/endpoints_advert.py
- app/modules/campaign/endpoints_campaign.py
- app/modules/cinema/endpoints_cinema.py
- app/modules/raffle/endpoints_raffle.py
- enforce valid filenames before get_file_from_data() in multiple endpoints in advert, campaign, cinema, raffle
- enforce user authentication in read_advert_image()
> Valid filenames before get_file_from_data() security mitigations

- app/modules/loan/cruds_loan.py
- app/modules/loan/endpoints_loan.py
- app/modules/loan/models_loan.py
- app/modules/loan/schemas_loan.py
- migrations/versions/5-loan_return_date.py
This change is required for the PR https://github.com/aeecleclair/Titan/pull/310.
It should be merged after #360
> Add returned_date field in loan module

- migrations/versions/5-loan_return_date.py
- fix returned_date type
- replace DateTime.now() by end date so the loans will be a bit ordered
- fix for loop where we ask two elements but we select only one element in the query
> Fix loan migration

- app/modules/phonebook/cruds_phonebook.py
- app/modules/phonebook/models_phonebook.py
- app/modules/phonebook/schemas_phonebook.py
- app/modules/phonebook/types_phonebook.py
- migrations/versions/6-phonebook.py
- tests/test_phonebook.py
> Fix phonebook : kinds enum and types file

- app/app.py
- requirements-dev.txt
- requirements.txt
This PR bumps 
- `fastapi` to `110.1`
- `ruff` to `0.3.7`
- `httpx` to `0.27.0`
And removes the test workaround because we now use the latest version of Starlette that reverted `"Turn scope["client"] to None on TestClient`
> Bump fastapi, ruff and httpx

- .github/workflows/publish.yml
We are currently pushing on the registry at each commit on main.
We only need to push to the registry when there is a new release.
> Push to registry only on release

- .env.template
- app/app.py
- app/core/config.py
- app/core/security.py
- app/modules/calendar/endpoints_calendar.py
- app/utils/auth/providers.py
This PR fixes OpenAPI specs, with the aim to be fully compatible with several API clients like Hoppscotch.
This includes:
- the fix of an invalid endpoint, which should always start with `/` (see https://learn.openapis.org/specification/paths.html#the-endpoints-list)
- the fix of the invalid security scheme_name, which should match `^[a-zA-Z0-9\.\-_]+$` (see https://spec.openapis.org/oas/latest.html#fixed-fields-5)
- automatically set operationId to the path for each route
- add name and version to the OpenAPI specifications
- add `HYPERION_VERSION` and `MINIMAL_TITAN_VERSION_CODE` to .env
Remove `PostmanAuthClient`
> Fix OpenAPI specs

- app/core/cruds_core.py
- app/core/models_core.py
- app/types/core_data.py
- app/types/exceptions.py
- app/utils/tools.py
- tests/test_utils.py
We often need to store a unique row with a few values:
- the status of the campaign
- if some module is enabled
- the state of the amap service...
This PR add logic to store a few values per module in a global table: CoreData. The data will be serialized into JSON using a custom Pydantic schema.
> Add CoreData to store values in an unique row

- .github/workflows/lintandformat.yml
- .github/workflows/test.yml
This PR makes the Hyperion repo use `uv` during ci tests. `uv` is a replacement for `pip` written in rust.
Ideally, ci tests should now be quicker ! No expected breakage from this PR since we don't use special pip functionalities (see https://astral.sh/blog/uv)
We'll use the official setup python gh action with uv when it will be merged or implemented (see https://github.com/actions/setup-python/pull/818).
> enhancement: Use `uv` instead of `pip` during ci tests

- .env.test
- .github/workflows/test.yml
- .gitignore
- migrations/versions/0-6-init.py
- migrations/versions/8-recommendation_primary_key.py
- migrations/versions/9-external_users.py
- pyproject.toml
- tests/commons.py
- tests/conftest.py
- tests/test_PH.py
- tests/test_advert.py
- tests/test_amap.py
- tests/test_auth.py
- tests/test_booking.py
- tests/test_calendar.py
- tests/test_campaign.py
- tests/test_cinema.py
- tests/test_core.py
- tests/test_flappybird.py
- tests/test_groups.py
- tests/test_loan.py
- tests/test_migrations.py
- tests/test_notification.py
- tests/test_phonebook.py
- tests/test_raffle.py
- tests/test_ratelimit.py
- tests/test_recommendation.py
- tests/test_users.py
- tests/test_utils.py
Fix #403 
Add Postgresql databse support for tests. Use a TestAppClient per test file, to prevent tests from a module to impact other modules
Configure a Postgresql database for the test workflow.
Run tests with Postgresql. Run migration tests with SQLite and Postgresql.
> Use postgresql for tests

- pyproject.toml
- requirements-dev.txt
See the split of rule ASYN101 in [version 5.0.0](https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#050)
> Bump ruff to version 0.5.2

- app/app.py
Allow to drop existing tables of already deleted schemas. This usually happen when switching git branches without running downgrade migrations
> Drop all tables based on db schema instead of models

- app/core/users/endpoints_users.py
- app/utils/tools.py
- requirements-common.txt
Use jaro_winkler similarity from jellyfish module instead of rapidfuzz. It has the same speed and better results
> Use jaro_winkler similarity instead of rapidfuzz

- app/app.py
- app/core/auth/endpoints_auth.py
- app/types/exceptions.py
to be able to raise custom errors instead of returning generic JSONResponse.
This change allows us to treat them as other `HTTPExceptions` in handlers and openapi schema
> Add ContentHTTPException and AuthHTTPException

- Dockerfile
- README.md
- app/app.py
- app/core/config.py
- app/dependencies.py
- docker-compose.yaml
- gunicorn.conf.py
- pyproject.toml
- disable default Gunicorn logger handlers to use our custom loggers
- remove `--preload` flag which break our async Queue logger handlers
- allow to prevent db init on Hyperion startup using an env variable
- add a Gunicorn on_starting hook to init the db
> Fix loggers and db initialization when using multiple Gunicorn workers

- app/app.py
- app/dependencies.py
- migrations/env.py
to prevent an error `Database engine is not initialized`
> Init db engine on Hyperion launch

- app/app.py
- app/utils/initialization.py
- tests/test_migrations.py
If we don't drop the test database before migration tests, missing columns won't be detected
This was broken since https://github.com/aeecleclair/Hyperion/pull/450
> Drop test db before migration tests

- app/modules/cdr/cruds_cdr.py
- app/modules/cdr/endpoints_cdr.py
- app/modules/recommendation/cruds_recommendation.py
to prevent `False` values to be interpreted as not provided fields
Related to #355
> Use model_fields_set to check if at least a field is to be updated

- app/modules/raid/endpoints_raid.py
- tests/test_raid.py
Allow to force the generation of all teams pdf
> RAID: Generate PDF

- app/core/users/endpoints_users.py
- app/utils/tools.py
This PR improves users fuzzy search results.
Searching algorithm is refactored in a more simple way:
- for each user: 
- attribute a score based on the query, the user attributes and a similarity algorithm
- insert the score and its corresponding user in a sorted list
- remove the lowest score of the list if its size is superior to the `limit` parameter (thus, always keeping the list sorted with the `N=limit` best results)
The score of each user correspond to the highest Jaro-Winkler similarity between the query and:
- firstname
- name
- firstname + name
- name + firstname
- nickname (if exists)
This method aims to fit real searches: queries are often related to one of these 5 strings, but we don't know which one. The higher the similarity is between the query and one of them, the more …
> Users fuzzy search enhancements

- .github/workflows/lintandformat.yml
instead of having two workflows named test
> Rename lintandformat workflow

- app/modules/advert/endpoints_advert.py
- prevent non-admin users from creating advertisers
- updated comment for `read_advertisers()`
> fix(advert): prevent non-admin users from creating advertisers

- app/types/exceptions.py
- app/utils/validators.py
- tests/test_users.py
to let FastAPI return Pydantic ValidationError instead of crashing
> Raise ValueError in phone validator

- app/app.py
- migrations/versions/26-account_types.py
> Fix: Account type refactoring CoreData migration

- requirements-common.txt
- requirements-dev.txt
> Change requirements

- app/utils/auth/providers.py
Postman and Swagger now always pass PKCE parameters in auth request using a client secret
> APIToolAuthClient: Allow to pass pkce parameters with client secret

- app/utils/auth/providers.py
Because Trello boards with several people aren't free anymore, BDE's president Larry asked last Tuesday for a Trello alternative for kanban boards, with possible MyECL integration. Here is the auth client class.
Goes hand in hand with [compose#137](../../compose/pull/137)
> Add PlankaAuthClient

- .github/workflows/codeql.yml
* No PR can be merged, unless an admin makes use of his power to bypass the requirements.
* Because *Analyze (python)* and *CodeQL* are stuck as "pending checks", since:
* They are expected to run
* They don't run: the default config (overridden by this YAML) made CodeQL be triggered only on push main
* We want those workflows to be triggered on PRs like *lint and format* and *test*.
* I open a PR so that this YAML can be reviewed.
> Fix attempt: run "expected" workflows

- app/core/auth/cruds_auth.py
- app/core/users/endpoints_users.py
Currently, is someone account is compromised, the user can not log out all active sessions.
Due to the use of a JWT we can not revoke active access token, but as they have a limited duration they will automatically expire after some time.
We should revoke refresh token to ensure that clients won't be able to get a new access token.
As a consequence the user changing its password in settings will be logged out of the app, but not immediately, only after the expiration of its refresh token
> Revoke refresh token on password change

- .env.test
- app/core/myeclpay/endpoints_myeclpay.py
- app/core/payment/payment_tool.py
- app/core/payment/types_payment.py
- app/core/utils/config.py
- app/dependencies.py
- app/modules/cdr/endpoints_cdr.py
- app/modules/raid/endpoints_raid.py
- app/types/exceptions.py
- tests/commons.py
- tests/conftest.py
- tests/test_payment.py
> feat: support multiple HelloAsso configurations

- app/modules/cdr/endpoints_cdr.py
* No reason to hide it
* Purpose: display the cdr year in Siarnaq :
* in order not to hard-code it (changing it every year is bad)
* in order to know easily the year Siarnaq thinks it is and catch it early if wrong
* Possibly do the same with the status (for the same reasons: pretty annoying to have to use admin rights to be sure of the actual status)
> Make CdR coredata public
